version: 1
frontend:
  phases:
    build:
      commands:
        - cd client
        - npm install
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*